config/routes.rb
Rails.application.routes.draw do
  resources :categories

  resources :users

  resources :sessions, only: [:new, :create, :destroy]

  get '/sign-in' => 'sessions#new'
  
  delete '/sign-out' => 'sessions#destroy'

  resources :posts

  root 'posts#index'

  get 'site/about'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  accepts_nested_attributes_for :posts

  has_secure_password
  validates_format_of :email,:with => /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/
  validates_uniqueness_of :email
  validates :password, presence: true
  validates :password_confirmation, presence: true
end

app/models/users.rb
class Users < ActiveRecord::Base
  has_secure_password
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, post_attributes: [:title, :body])
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.slim
.form-default.col-sm-6
  = form_for @user, :html => {class: 'rounded'} do |f|
    h2 Create an account
    - if @user.errors.any?
      #error_explanation
        h3 = "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
        ul
          - @user.errors.full_messages.each do |message|
            li = message
    .field
      = f.label :email
      = f.text_field :email, placeholder: "Email address", required: true
    .field
      = f.label :password
      = f.password_field :password, placeholder: "Password", required: true
    .field
      = password_field_tag 'user[password_confirmation]', nil, placeholder: 'Confirm Password', required: true
    .field
      = hidden_field_tag 'user[admin]', false
    .actions = f.submit

.col-sm-6
  div.prompt.rounded
    h3 Already a member?
    = link_to "Sign In", sign_in_path, class: 'btn'

app/views/users/edit.html.slim
h1 Editing user

== render 'form'

= link_to 'Show', @user
'|
= link_to 'Back', users_path

app/views/users/index.html.slim
h1 Listing users

table
  thead
    tr
      th Email
      th Password
      th
      th
      th

  tbody
    - @users.each do |user|
      tr
        td = user.email
        td = user.password
        td = link_to 'Show', user
        td = link_to 'Edit', edit_user_path(user)
        td = link_to 'Destroy', user, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New User', new_user_path

app/views/users/new.html.slim
== render 'form'

.clearfix
  = link_to 'Back', users_path

app/views/users/show.html.slim
h2.page-heading = @user.email

- if @user.posts
  - @user.posts.each do |post|
    .post.col-md-6
      h3 = post.title
      blockquote = post.body.html_safe