config/routes.rb
Rails.application.routes.draw do
  resources :categories

  resources :users

  resources :sessions, only: [:new, :create, :destroy]

  get '/sign-in' => 'sessions#new'
  
  delete '/sign-out' => 'sessions#destroy'

  resources :posts

  root 'posts#index'

  get 'site/about'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :user_signed_in?, :category_list, :authorize

  private

  def current_user
    User.find_by(id: session[:user_id])
  end

  def user_signed_in?
    !!current_user
  end

  def category_list
    @cats = []
    Category.all.each do |cat|
      @cats.push({:id => cat.id, :title => cat.title})
    end
    return @cats
  end

  def authorize
    redirect_to new_user_path if !user_signed_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable column, title=nil
    title ||= column.titleize
    direction = sort_direction == "desc" ? "asc" : "desc"
    link_to title, params.merge(sort: column, direction: direction, page:nil, remote: true)
  end
end

app/views/application/_header.html.slim
doctype html
html
  head

    title CarHackResource
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  body
    - flash.each do |type, message|
      div class=["flash" , type]
        p = message
        div.dismiss X
    - if user_signed_in? && current_user.admin
        .admin-panel
          span Admin Links
          nav
            ul
              li = link_to "Categories Home", categories_path
    header
      nav
        ul.nav.container
          li= link_to root_path
            h1 SkillSoup
          - if user_signed_in?
            li.pull-right = link_to "Sign Out", sign_out_path, method: :delete
            li.pull-right = link_to "Profile", user_path(current_user), method: :get
          - else
            li.pull-right = link_to "Sign In", sign_in_path
            li.pull-right = link_to "Create Account", new_user_path

app/views/application/_postfeed.html.slim
section.posts.transitions-enabled#posts
  - @posts.each do |post|
    .box.panel.panel-default.home-post
      .panel-body
        h2.post-title = post.title
        h3.post-date = post.created_at.stamp('Aug 04')
        blockquote.froala-view = post.body.truncate(140).html_safe
      - if post.image
        = link_to post.image.url
          = image_tag(post.image)

= paginate @posts, remote: true

app/views/application/_sort_by.html.slim
span Sort by:
= sortable "created_at"
= sortable "title"